baseURL = 'https://uptimer.myuptime.info/' # Global URL for the site
languageCode = 'en-us'
title = 'Uptimer'
theme = "hugo-book"

[params]
BookSection = "*" # Only include specific sections in menu
BookSearch = true # Enable search
BookPortableLinks = true # Make internal links portable
BookToC = true # Enable Table of Contents on pages

# Versioning configuration
[params.versions]
# The default version that will be shown when no version is specified
default = "1.0.0"
# Available versions in order (newest first)
available = ["1.0.0", "0.2.0"]
# Latest version (for redirects and canonical URLs)
latest = "1.0.0"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "GitHub"
url = "https://github.com/myuptime-info/uptimer" # GitHub repository URL
weight = 20

# Optional: Disable "posts" section if you don't need a blog-like section
[taxonomies]
category = "categories"
tag = "tags"

# Explicitly disable posts section
[params.BookSections]
posts = false

# Disable section pages for posts
disableKinds = ["section"]
ignoreFiles = ["content/posts"]
