services:
  uptimer-ui:  # service website
    image: myuptime/uptimer
    command: ["server", "--services", "ui"]
    ports:
      - "2517:2517"
    volumes:
      - ./data/server:/data
  uptimer-grpc:  # grpc server
    image: myuptime/uptimer
    command: ["server", "--services", "grpc"]
    environment:
      UPTIMER__GRPC__PORT: 2518
    ports:
      - "2518:2518"
    volumes:
      - ./data/server:/data
  uptimer-jobs:  # background jobs
    image: myuptime/uptimer
    command: ["server", "--services", "availabilities"]
    volumes:
      - ./data/server:/data

  worker1:  # worker1
    image: myuptime/uptimer
    volumes:
      - ./data/worker1:/data
    environment:
      UPTIMER__WORKER__GRPC_SERVER: uptimer-grpc:2518
      UPTIMER__WORKER__GRPC_USE_TLS: false
    command: worker
    depends_on:
      - uptimer-grpc

  worker2:  # worker2
    image: myuptime/uptimer
    volumes:
      - ./data/worker2:/data
    environment:
      UPTIMER__WORKER__GRPC_SERVER: uptimer-grpc:2518
      UPTIMER__WORKER__GRPC_USE_TLS: false
    command: worker
    depends_on:
      - uptimer-grpc
